root = "."
testdata_dir = "testdata"
tmp_dir = "bin/debug"

[build]
  args_bin = []
  bin = "bin/debug/agartha"
  full_bin = "GIN_MODE=debug bin/debug/agartha serve"
  cmd = "GIN_MODE=debug go build -o ./bin/debug/agartha ."
  post_cmd = ["ps | awk '!/awk/&&/agartha serve/ { print $1 }' | xargs -I {} kill {}"]
  delay = 1000
  exclude_dir = ["assets", "tmp", "vendor", "testdata", "web", "bin", "server/docs", "extras", "docker-compose", ".pnpm-store", ".github"]
  exclude_file = [".gitignore", ".dockerignore", ".containerignore", "LICENSE", "Makefile"]
  exclude_regex = ["_test.go", "Dockerfile", "docker-compose", "example", ".md"]
  exclude_unchanged = false
  follow_symlink = false
  include_dir = []
  include_ext = ["go", "yaml", "toml"]
  kill_delay = "0s"
  log = "build-errors.log"
  send_interrupt = true
  stop_on_error = true

[color]
  app = ""
  build = "yellow"
  main = "magenta"
  runner = "green"
  watcher = "cyan"

[log]
  time = true

[misc]
  clean_on_exit = false

[screen]
  clear_on_rebuild = true
